### ISSUE TITLE
How do I build gdx-gltf-demo.jar?

### ISSUE THREAD

**Issue by travisfw** [mgsx-dev/gdx-gltf#20]
The readme ( https://github.com/mgsx-dev/gdx-gltf/blob/master/demo/README.md ) says to run gdx-gltf-demo.jar. I tried `gradlew assembleRelease` and `gradlew jar` and couldn't find `gdx-gltf-demo.jar`. I haven't worked with multi-module gradle setups much, but I tried going to demo/desktop and running `gradle tasks` (yes, with gradle 2.14.1 🤦), and it failed with a nondescript NPE:
```
:demo:desktop:tasks FAILED

FAILURE: Build failed with an exception.

* What went wrong:
java.lang.NullPointerException (no error message)
```

**Comment by mgsx-dev** [comment]
as any libgdx project, you need to run `gradlew :demo:desktop:dist`, you'll find the jar file in **demo/desktop/build/libs** folder.
due to old gradle version, i'm not sure you can use latest java versions, should be fine with java 8 though.
Let me know if it works for you, i'll add it to the readme.
Thank you for your feedback.

**Comment by travisfw** [comment]
Okay I got it running with
```
./gradlew clean :demo:desktop:dist
# or just `gradlew dist` to build the whole thing, as mentioned, but then I had to set up the Android sdk
java -jar demo/desktop/build/libs/desktop-0.0.1-SNAPSHOT.jar
```
But I got an NPE from GLTFDemo. I put in an assertion and found that rootModel is null on line 596, but the name of the jar is different than expected. Am I doing it right?

**Comment by mgsx-dev** [comment]
I can reproduce the issue (sorry about that), it's a timing issue with remote loading models from khronos github (default mode) so it'd better to use local mode, see [https://github.com/mgsx-dev/gdx-gltf/tree/2d1374fd3c262e22a37bb74ede2db337bb8be2ae/demo#run-desktop-examples](how to run it locally).

Since the demo was mainly here for testing purpose, i didn't hardly tested all the cases recently. However, it becomes useful and considered more as a "GLTF model viewer" so i should probably totally reconsider this loading process.

**Comment by mgsx-dev** [comment]
about JAR name, it doesn't matter, i rename it when attaching to a release to avoid changes in documentation.

**Comment by travisfw** [comment]
I should have included the output (including stack trace) before. It shows that the NPE is encountered when parsing [morphing.gltf](https://github.com/mgsx-dev/gdx-gltf/blob/master/demo/android/assets/models/Morphing/glTF/morphing.gltf )
```
[GLTFDemo] loading morphing.gltf
[GLTFDemo] loaded models/Morphing/glTF/morphing.gltf
[GLTF Inspector] [Scene Graph] scenes:1 nodes:1 empty:0 
[GLTF Inspector] [Mesh] count:1 parts:1 Vertices:216 Tris:108 Rendered:108 
[GLTF Inspector] [Materials] count:1 
Exception in thread "LWJGL Application" java.lang.NullPointerException
	at net.mgsx.gltf.demo.GLTFDemo.validateShaders(GLTFDemo.java:596)
	at net.mgsx.gltf.demo.GLTFDemo.render(GLTFDemo.java:914)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:233)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:128)
```

**Comment by travisfw** [comment]
Thanks very much for your support. I've built the demo and downloaded the glTF samples, and can now easily run on desktop. 👌

**Comment by mgsx-dev** [comment]
i'm keeping it open because of the bug in the demo and lack of documentation, just as a reminder for me :-)
