### ISSUE TITLE
Runtime instance loading

### ISSUE THREAD

**Issue by rami-dabain** [mgsx-dev/gdx-gltf#30]
Is there a way to load player characters and control them independently?
I spawn models (currently converted from fbx-conv... not good) and i want to use gltf (as i do for the scene/map)
However having each actor/player in a separate scene is not very easy to manage and how bad is it for performance?

**Comment by dzikoysk** [comment]
You should be able to use loaded models without scenes. We can fetch loaded ModelInstance and handle them manually in a custom environment, just like you've used it with g3db files.

**Comment by mgsx-dev** [comment]
A Scene is a simple wrapper for both modelInstance and animationController basically.
You typically have 1 Scene per character, the same way you have 1 ModelInstance per character. Mainly because they are independent from each others : different transform matrix and different animation playback. Performances wise it would be bad to have all characters in the same model instance because you'd have to compute nodes transform for each running animations.

FYI ModelInstanceHack and AnimationControllerHack are not about vertices limits but for shape keys and animations with cubic interpolation. Libgdx supports mesh with 64k vertices now.

If you have more questions, please use libgdx discord server :-)
