### ISSUE TITLE
GL_OES_standard_derivatives extension or tangent vertex attribute required

### ISSUE THREAD

**Issue by rami-dabain** [mgsx-dev/gdx-gltf#31]
Unable to load scene in Android despite exporting tangents from Blender

![copped](https://user-images.githubusercontent.com/1197104/100540143-b705c500-323b-11eb-9012-8111ce36907b.png)

**Comment by mgsx-dev** [comment]
please make sure tangents are really exported. Sometimes Blender GLTF exporter can't calculate them and don't export them (eg. if there are some N-gons, if UVs missing, etc), some warning should appear in Blender error logs when exporting if it's the case.
You can also verify it in your gltf file directly (meshes section).
To fix that, you need to split your N-gons manually or triangulate your mesh before exporting in Blender.

Please let me know if that was the issue. If not, please post your gltf file (as a zip) in order to help me fixing the issue.

**Comment by rami-dabain** [comment]
Triangulation was the issue. Thanks for the tip!
