### ISSUE TITLE
Dynamic Environment / IBL possible?

### ISSUE THREAD

**Issue by cosmicdan** [mgsx-dev/gdx-gltf#60]
Hi,

First a quick intro - I am new to game coding from scratch but very experienced in Java, thank you so much for this lib. Following xoppa's 3D tutorial has been very straightforward and I find it easier to work in 3D space than 2D space. You've made modern 3D rendering VERY easy!

Apologies if this isn't the best place for questions/support, but after learning about IBL and PBR's I feel I have a pretty good grasp on it, and it's awesome that we can build IBL's in code which is what I intend to do...

...but is there a mechanism in place to switch/modify an environment in a Scene that can be done in real-time? For example, a day-night cyclem or when the player walks into a building from outside. It's probably simple enough to move the IBL light around, but I'd eventually like to change the IBL cube for my game scene every X frames. 

So what would be the best way to do this? My educated guess would be a custom version of SceneManager that has multiple Environment fields, and to draw them blended somehow (or just select one to draw) based on whatever (in most cases the cam position but it'd be up to the render loop to decide which environment should be drawn).

Does that sound right to you?

Thanks so much in advance for your input. Ultimately I would like to test the feasibility of true global lighting; i.e. building IBR's in realtime based on the actual visible game world (or rather, neighboring map chunks and the current weather and such) - though I'll have to build a decent game world before I can work on that. It's very exciting to already be this close, thanks again for the work you've done!

P.S. If you're not sure then no worries, I can spend some time measuring the time/cost of building IBR's and switching the environment - I'm mostly just wondering if you have any clue on what would be the most efficient way of changing IBR's quickly - multiple Environments or multiple SceneManagers or maybe something else? What would most likely need to be buffered/cached? You would likely already have an idea of the cost of stuff so again, thanks in advance for anything you might have to add since I'm not an expert :)

**Comment by mgsx-dev** [comment]
@cosmicdan the best place to chat about such topic is [the libGDX discord server](https://libgdx.com/community/), we have a 3D channel that fit such topic, you can find me there ;-).

I didn't implemented such thing myself, but i think that's doable. I don't know what would be the best between mixing 2 IBLs in realtime or generating one IBL in realtime. They both have pros and cons.
Mixing 2 IBLs require to modify PBR shader (having custom Shader, ShaderProvider classes and GLSL code).
Generating 1 IBL in "realtime" is something already done in IBLComposer application, but depending on settings, it takes significant time to run shaders.

I'll close the issue now because i don't plan to have it implemented in the library. Feel free to ping me on Discord to continue the discussion.

Thank you for your support.
